from setuptools import setup, find_packages

setup(
    name="rpi-robot-hat-lib",
    version="1.2.5",
    description="Raspberry Pi Robot Hat Library with encoder support",
    long_description="A comprehensive library for controlling Raspberry Pi robot hat with motor control, encoder feedback, sensor integration, and autonomous navigation capabilities.",
    long_description_content_type="text/plain",
    author="JIaLeChye",
    author_email="jialecjl2016@outlook.com",
    url="https://github.com/JIaLeChye/MobileRobot",
    packages=find_packages(),
    py_modules=["RPi_Robot_Hat_Lib", "Encoder"],
    install_requires=[
        "smbus2>=0.4.0",
        "rpi-lgpio>=0.4",
    ],
    python_requires=">=3.7",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Education",
        "License :: OSI Approved :: MIT License",
        "Operating System :: POSIX :: Linux",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: System :: Hardware",
        "Topic :: Education",
        "Topic :: Scientific/Engineering",
    ],
    keywords="raspberry-pi, robotics, motor-control, sensors, automation",
)
